[v1]
"cargo-audit 0.18.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-auditable 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-auditable"]
"cargo-edit 0.11.11 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.65 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-watch 8.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cornucopia 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cornucopia"]
"create-tauri-app 3.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-create-tauri-app"]
"diesel_cli 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"sshx 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sshx"]
"tauri-cli 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri"]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"wasm-pack 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
"x 0.1.1 (path+file:///Users/inust/CLionProjects/rust/src/tools/x)" = ["x"]
"zellij 0.37.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.9.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
